name: Playwright Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      VITE_APP_MODE: automated_tests
      VITE_APP_PORT: 3000
      VITE_APP_BASE_URL: http://localhost:3000/
      VITE_CORE_API_BASE_URL: http://localhost:5000/api/v1
      VITE_AWS_COGNITO_USER_POOL_ID: local_0tm1eyyS
      VITE_AWS_COGNITO_CLIENT_ID: dy84cymh67njie4bdru9g3rk2
      VITE_AWS_COGNITO_ENDPOINT: http://localhost:9229
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "18.x"
      - name: Install dependencies
        run: npm i
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Pre-build Step (Compile TypeScript)
        run: npm run pretest
      - name: Run Playwright tests
        run: npx playwright test
      - name: Upload Playwright Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright/playwright-report/
          retention-days: 30
      - name: Upload Playwright Test Assets
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-test-results
          path: |
            playwright/test-results/
            playwright/playwright-report/
          retention-days: 30
      - name: Upload Videos as Artifacts (optional)
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-videos
          path: playwright/test-results/
          retention-days: 30
